# Generated by Django 5.1.3 on 2025-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="picture",
            field=models.ImageField(default=None, upload_to="static/bio_pics"),
        ),
    ]
