# Generated by Django 5.1.3 on 2025-01-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_population_therapist_populations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Credential",
            new_name="Certification",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="credentials",
            new_name="certifications",
        ),
    ]
