# Generated by Django 5.1.3 on 2025-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_rename_credential_certification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
    ]
