# Generated by Django 5.1.3 on 2025-01-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurancePageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_text", models.TextField()),
            ],
        ),
    ]
