# Generated by Django 5.1.3 on 2025-01-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_rename_insurance_text_insurancepagetext_section_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurancepagetext",
            old_name="name_of_section",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="insurancepagetext",
            old_name="section_text",
            new_name="text",
        ),
    ]
