# Generated by Django 5.1.3 on 2025-01-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_rename_name_of_section_insurancepagetext_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
