# Generated by Django 5.1.3 on 2025-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="accepting_clients",
            field=models.CharField(default="Accepting new clients", max_length=50),
            preserve_default=False,
        ),
    ]
