# Generated by Django 5.1.3 on 2025-04-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_therapist_accepting_clients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name_plural": "About us"},
        ),
    ]
