# Generated by Django 5.1.3 on 2025-04-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_aboutus_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapist",
            name="picture",
        ),
        migrations.AddField(
            model_name="therapist",
            name="picture_filename",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
