# Generated by Django 5.1.3 on 2025-04-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_remove_therapist_picture_therapist_picture_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="picture_filename",
            field=models.CharField(default="ofarrell_ryan.jpg", max_length=50),
        ),
    ]
